services:
  api:
    image: ${DOCKER_REGISTRY-}banterapi
    build:
      context: .
      dockerfile: Banter.API/Dockerfile
    environment:
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      ConnectionStrings__Redis: "cache:6379,password=${REDIS_PASSWORD},abortConnect=false"

  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:${REDIS_VERSION}
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    
  seq:
    image: datalust/seq:${SEQ_VERSION}
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD}

    ports:
      - "127.0.0.1:${SEQ_PORT}:80"

    volumes:
      - seq-data:/data

volumes:
  db_data:
  redis_data:
  seq-data:

